[tool.poetry]
name = "a-maze-ing"
version = "0.1.0"
description = "Proyecto de generación de laberintos de 42"
authors = ["agarcia2 <agarcia2@student.42barcelona.com>, ehorvat <ehorvat@student.42barcelona.com>"]
readme = "README.md"
packages = [{include = "mazegen"}]
package-mode = true 

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0"
mypy = "^1.0"
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
